export const substanceFormattingList = [
    { label: "314 - Dermatophagoides farinae", value: "314 - Dermatophagoides farinae" },
    { label: "315 - Dermatophagoides pteronyssinus", value: "315 - Dermatophagoides pteronyssinus" },
    { label: "317 - Lepidoglyphus destructor", value: "317 - Lepidoglyphus destructor" },
    { label: "318 - Tyrophagus putrescentiae", value: "318 - Tyrophagus putrescentiae" },
    { label: "324 - Glyciphagus domesticus", value: "324 - Glyciphagus domesticus" },
    { label: "325 - Acarus siro", value: "325 - Acarus siro" },
    { label: "326 - Euroglyphus Maynei", value: "326 - Euroglyphus Maynei" },
    { label: "333 - Pyroglyphus africanus", value: "333 - Pyroglyphus africanus" },
    { label: "335 - Blomia tropicalis", value: "335 - Blomia tropicalis" },
    { label: "330 - Storage mites", value: "330 - Storage mites" },
    { label: "350 - House dust mites", value: "350 - House dust mites" },
    { label: "505 sheep wool", value: "505 sheep wool" },
    { label: "507 - Cat epithelia", value: "507 - Cat epithelia" },
    { label: "508 - Goat epitelia", value: "508 - Goat epitelia" },
    { label: "509 - Dog epithelia", value: "509 - Dog epithelia" },
    { label: "510 - Guinea pig epithelia", value: "510 - Guinea pig epithelia" },
    { label: "511 - Hamster epithelia", value: "511 - Hamster epithelia" },
    { label: "512 - Rabbit epithelia", value: "512 - Rabbit epithelia" },
    { label: "513 - Rat epithelia", value: "513 - Rat epithelia" },
    { label: "514 - Mouse epithelia", value: "514 - Mouse epithelia" },
    { label: "516 - Horse epithelia", value: "516 - Horse epithelia" },
    { label: "505 - Feather mixture", value: "505 - Feather mixture" },
    { label: "301 - Blatella germanica", value: "301 - Blatella germanica" },
    { label: "303 - Corn moth", value: "303 - Corn moth" },
    { label: "307 - Mosquito", value: "307 - Mosquito" },
    { label: "400 - Alternaria alternata", value: "400 - Alternaria alternata" },
    { label: "402 - Botrytis cinerea", value: "402 - Botrytis cinerea" },
    { label: "405 - Trichothecium roseum", value: "405 - Trichothecium roseum" },
    { label: "406 - Aspergillus nidulans", value: "406 - Aspergillus nidulans" },
    { label: "407 - Chaetomium globosum", value: "407 - Chaetomium globosum" },
    { label: "408 - Aspergillus niger", value: "408 - Aspergillus niger" },
    { label: "409 - Epicoccum purpurascens", value: "409 - Epicoccum purpurascens" },
    { label: "411 - Fusarium solani", value: "411 - Fusarium solani" },
    { label: "412 - Cladosporium cladosporioides", value: "412 - Cladosporium cladosporioides" },
    { label: "413 - Helminthosporium halodes", value: "413 - Helminthosporium halodes" },
    { label: "416 - Aspergillus fumigatus", value: "416 - Aspergillus fumigatus" },
    { label: "417 - Mucor racemosus", value: "417 - Mucor racemosus" },
    { label: "422 -Penicillium digitatum", value: "422 -Penicillium digitatum" },
    { label: "423 -Penicillium expansum", value: "423 -Penicillium expansum" },
    { label: "424 -Penicillium notatum", value: "424 -Penicillium notatum" },
    { label: "425 - Aureobasidium pullulans", value: "425 - Aureobasidium pullulans" },
    { label: "426 - Rhizopus nigricans", value: "426 - Rhizopus nigricans" },
    { label: "430 - Cladosporium herbarum extract", value: "430 - Cladosporium herbarum extract" },
    { label: "432 - Pleospora herbarum", value: "432 - Pleospora herbarum" },
    { label: "435 - Trichophyton rubrum", value: "435 - Trichophyton rubrum" },
    { label: "436 - Ustilago avenae", value: "436 - Ustilago avenae" },
    { label: "438 - Ustilago Holci", value: "438 - Ustilago Holci" },
    { label: "439 - Ustilago Tritici", value: "439 - Ustilago Tritici" },
    { label: "440 - Ustilago zeae", value: "440 - Ustilago zeae" },
    { label: "447 - Serpula lacrymans", value: "447 - Serpula lacrymans" },
    { label: "401 - Aspergillus mix", value: "401 - Aspergillus mix" },
    { label: "414 - Cladosporium mix", value: "414 - Cladosporium mix" },
    { label: "422 - Penicillium mix", value: "422 - Penicillium mix" },
    { label: "446 - Ustilago mix", value: "446 - Ustilago mix" },
    { label: "403 - Candida albicans", value: "403 - Candida albicans" },
    { label: "410 - Epidermophyton floccosum", value: "410 - Epidermophyton floccosum" },
    { label: "428 - Saccharomyces cerevisiae", value: "428 - Saccharomyces cerevisiae" },
    { label: "445 - Saccharomyces mix", value: "445 - Saccharomyces mix" },
    { label: "601 - Agrostis capillaris L.", value: "601 - Agrostis capillaris L." },
    { label: "610 - Avena sativa L.", value: "610 - Avena sativa L." },
    { label: "611 - Arrhenatherum elatius", value: "611 - Arrhenatherum elatius" },
    { label: "614 - Triticum aestivum", value: "614 - Triticum aestivum" },
    { label: "624 - Elymus repens L.", value: "624 - Elymus repens L." },
    { label: "627 - Dactylis glomerata L.", value: "627 - Dactylis glomerata L." },
    { label: "630 -Festuca pratensis Hudson", value: "630 -Festuca pratensis Hudson" },
    { label: "631 - Anthoxanthum odoratum L.", value: "631 - Anthoxanthum odoratum L." },
    { label: "637 -Holcus lanatus", value: "637 -Holcus lanatus" },
    { label: "638 - Lolium perenne L.", value: "638 - Lolium perenne L." },
    { label: "642 - Zea mays L.", value: "642 - Zea mays L." },
    { label: "652 - Hordeum vulgare L.", value: "652 - Hordeum vulgare L." },
    { label: "658 - Poa pratensis L.", value: "658 - Poa pratensis L." },
    { label: "660 - Paspalum notatum", value: "660 - Paspalum notatum" },
    { label: "661 - Phleum pratense L.", value: "661 - Phleum pratense L." },
    { label: "671 - Secale cereale L.", value: "671 - Secale cereale L." },
    { label: "674 - Sorghum halepense whole", value: "674 - Sorghum halepense whole" },
    { label: "705 - Cynodon dactylon (L.) Pers.", value: "705 - Cynodon dactylon (L.) Pers." },
    { label: "687 - 4 Cereals", value: "687 - 4 Cereals" },
    { label: "688 - 5 grasses", value: "688 - 5 grasses" },
    { label: "689 - 12 grasses", value: "689 - 12 grasses" },
    { label: "690 - 5 grasses\/ 4 Cereals", value: "690 - 5 grasses\/ 4 Cereals" },
    { label: "701 - 3 grasses", value: "701 - 3 grasses" },
    { label: "762 - 5 grasses\/ rye", value: "762 - 5 grasses\/ rye" },
    { label: "609 - Alnus glutinosa L", value: "609 - Alnus glutinosa L" },
    { label: "615 - Betula", value: "615 - Betula" },
    { label: "619 - Carpinus betulus L.", value: "619 - Carpinus betulus L." },
    { label: "620 - Castanea sativa", value: "620 - Castanea sativa" },
    { label: "621 - Quercus robur L.", value: "621 - Quercus robur L." },
    { label: "626 - Cupressus sempervirens L.", value: "626 - Cupressus sempervirens L." },
    { label: "629 - Acer pseudoplatanus L.", value: "629 - Acer pseudoplatanus L." },
    { label: "632 - Fraxinus excelsior L.", value: "632 - Fraxinus excelsior L." },
    { label: "634 - Juniperus communis L.", value: "634 - Juniperus communis L." },
    { label: "635 - Fagus sylvatica L.", value: "635 - Fagus sylvatica L." },
    { label: "644 - Aesculus hyppocastanum L.", value: "644 - Aesculus hyppocastanum L." },
    { label: "645 - Acacia dealbata link", value: "645 - Acacia dealbata link" },
    { label: "647 - Morus alba L.", value: "647 - Morus alba L." },
    { label: "648 - Prosopis glandilosa Torr", value: "648 - Prosopis glandilosa Torr" },
    { label: "649 -Corylus avellana L.", value: "649 -Corylus avellana L." },
    { label: "650 - Juglans regia L.", value: "650 - Juglans regia L." },
    { label: "651 - Olea europaea L.", value: "651 - Olea europaea L." },
    { label: "653 - Ulmus campestris L.", value: "653 - Ulmus campestris L." },
    { label: "659 -Populus alba", value: "659 -Populus alba" },
    { label: "662 - Pinus sylvestris L.", value: "662 - Pinus sylvestris L." },
    { label: "666 - Platanus acerifolia", value: "666 - Platanus acerifolia" },
    { label: "667 - Robinia pseudoacacia L.", value: "667 - Robinia pseudoacacia L." },
    { label: "668 - Phoenix dactylifera", value: "668 - Phoenix dactylifera" },
    { label: "669 - Salix caprea L.", value: "669 - Salix caprea L." },
    { label: "675 - Sambucus nigra L.", value: "675 - Sambucus nigra L." },
    { label: "677 - Tilia", value: "677 - Tilia" },
    { label: "680 - Ligustrum vulgare L.", value: "680 - Ligustrum vulgare L." },
    { label: "681 - Cupressus arizonica whole", value: "681 - Cupressus arizonica whole" },
    { label: "716 - Juniperus ashei Buchholz", value: "716 - Juniperus ashei Buchholz" },
    { label: "696 - Fagaceae", value: "696 - Fagaceae" },
    { label: "702 - Betulaceae", value: "702 - Betulaceae" },
    { label: "715 - Oleaceae", value: "715 - Oleaceae" },
    { label: "717 - Salicaceae", value: "717 - Salicaceae" },
    { label: "718 - Tree mixtures", value: "718 - Tree mixtures" },
    { label: "752 - 3 Trees", value: "752 - 3 Trees" },
    { label: "106 - Wheat flour", value: "106 - Wheat flour" },
    { label: "161 - Rye flour", value: "161 - Rye flour" },
    { label: "176 - Lupin flour", value: "176 - Lupin flour" },
    { label: "195 - Alpha amylase", value: "195 - Alpha amylase" },
    { label: "903 - Latex", value: "903 - Latex" },
    { label: "913 - Bagasse", value: "913 - Bagasse" },
    { label: "917 - sawdust", value: "917 - sawdust" },
    { label: "602 - Amaranthus retroflexus L.", value: "602 - Amaranthus retroflexus L." },
    { label: "604 - Ambroisia artemisiifolia L.", value: "604 - Ambroisia artemisiifolia L." },
    { label: "605 - Artemisia vulgaris L.", value: "605 - Artemisia vulgaris L." },
    { label: "623 - Chenopodium album L.", value: "623 - Chenopodium album L." },
    { label: "625 - Brassica napus L.", value: "625 - Brassica napus L." },
    { label: "636 - Humulus lupulus L.", value: "636 - Humulus lupulus L." },
    { label: "641 - Medicago sativa L", value: "641 - Medicago sativa L" },
    { label: "643 - Chrysanthemum leucantemum L.", value: "643 - Chrysanthemum leucantemum L." },
    { label: "646 - Brassica nigra", value: "646 - Brassica nigra" },
    { label: "654 -Urtica dioica L.", value: "654 -Urtica dioica L." },
    { label: "655 - Rumex acetosa L.", value: "655 - Rumex acetosa L." },
    { label: "657 - Parietaria officinalis L.", value: "657 - Parietaria officinalis L." },
    { label: "664 - Taraxacum officinale", value: "664 - Taraxacum officinale" },
    { label: "665 - Plantago lanceolata L.", value: "665 - Plantago lanceolata L." },
    { label: "673 - Solidago canadensis L.", value: "673 - Solidago canadensis L." },
    { label: "678 - Helianthus annuus L.", value: "678 - Helianthus annuus L." },
    { label: "679 - Trifolium pratense L.", value: "679 - Trifolium pratense L." },
    { label: "708 - Parietaria judaica L.", value: "708 - Parietaria judaica L." },
    { label: "710 - Salsola kali L.", value: "710 - Salsola kali L." },
    { label: "706 - Weed mixture", value: "706 - Weed mixture" },
    { label: "714 - Chenopodiacees", value: "714 - Chenopodiacees" },
    { label: "719 - Compositae", value: "719 - Compositae" },
    { label: "Codeine phosphate", value: "Codeine phosphate" },
    { label: "Histamine dihydrochloride", value: "Histamine dihydrochloride" },
    { label: "Histamine dihydrochloride - DIVERCHIM", value: "Histamine dihydrochloride - DIVERCHIM" },
    { label: "Histamine dihydrochloride - LEBSA", value: "Histamine dihydrochloride - LEBSA" },
    { label: "319 - Apis mellifera venom", value: "319 - Apis mellifera venom" },
    { label: "320-Yellow Jacket venom (Vespula SPP)", value: "320-Yellow Jacket venom (Vespula SPP)" },
    { label: "321 - Wasp venom (Polistes SPP)", value: "321 - Wasp venom (Polistes SPP)" },
    { label: "111 - Coffee", value: "111 - Coffee" },
    { label: "140 - Mustard", value: "140 - Mustard" },
    { label: "165 - Tea leaf", value: "165 - Tea leaf" },
    { label: "172 - Aniseed", value: "172 - Aniseed" },
    { label: "177 - Cumin", value: "177 - Cumin" },
    { label: "178 - Curry", value: "178 - Curry" },
    { label: "180 - bay Laurel", value: "180 - bay Laurel" },
    { label: "182 - Nutmeg", value: "182 - Nutmeg" },
    { label: "183 - Paprika", value: "183 - Paprika" },
    { label: "184 - Black Pepper", value: "184 - Black Pepper" },
    { label: "185 - Thyme", value: "185 - Thyme" },
    { label: "196 - Sésame", value: "196 - Sésame" },
    { label: "707 - Sugar cane", value: "707 - Sugar cane" },
    { label: "105 Wholewheat flour", value: "105 Wholewheat flour" },
    { label: "136 Maize starch", value: "136 Maize starch" },
    { label: "149 Barley cream", value: "149 Barley cream" },
    { label: "160 Rice", value: "160 Rice" },
    { label: "179 Buckwheat flour", value: "179 Buckwheat flour" },
    { label: "181 Malt extract", value: "181 Malt extract" },
    { label: "186 - 7 cereals", value: "186 - 7 cereals" },
    { label: "143 - Egg white", value: "143 - Egg white" },
    { label: "144 - Egg yolk", value: "144 - Egg yolk" },
    { label: "145 - Egg (whole)", value: "145 - Egg (whole)" },
    { label: "100 - Lamb", value: "100 - Lamb" },
    { label: "157 - Pork", value: "157 - Pork" },
    { label: "158 - Chiken", value: "158 - Chiken" },
    { label: "101 - Artichoke", value: "101 - Artichoke" },
    { label: "112 - Carrot", value: "112 - Carrot" },
    { label: "114 - Celery", value: "114 - Celery" },
    { label: "121 - Spinach", value: "121 - Spinach" },
    { label: "128 - Green bean", value: "128 - Green bean" },
    { label: "146 - Onion", value: "146 - Onion" },
    { label: "153 - Pea", value: "153 - Pea" },
    { label: "156 - Potato", value: "156 - Potato" },
    { label: "167 - Tomato", value: "167 - Tomato" },
    { label: "170 - Garlic", value: "170 - Garlic" },
    { label: "190 - Soy", value: "190 - Soy" },
    { label: "102 - Coconut", value: "102 - Coconut" },
    { label: "103 - Banana fruit", value: "103 - Banana fruit" },
    { label: "109 - Peanut", value: "109 - Peanut" },
    { label: "110 - Cocoa", value: "110 - Cocoa" },
    { label: "117 - Lemon", value: "117 - Lemon" },
    { label: "123 - Strawberry", value: "123 - Strawberry" },
    { label: "137 - Melon fruit", value: "137 - Melon fruit" },
    { label: "141 -Hazelnut", value: "141 -Hazelnut" },
    { label: "142 - Walnut", value: "142 - Walnut" },
    { label: "147 - Olive fruit", value: "147 - Olive fruit" },
    { label: "148 - Orange", value: "148 - Orange" },
    { label: "151 - Peach fruit", value: "151 - Peach fruit" },
    { label: "155 - Appel fruit", value: "155 - Appel fruit" },
    { label: "169 - Apricot", value: "169 - Apricot" },
    { label: "171 - Almond", value: "171 - Almond" },
    { label: "187 - Passion fruit", value: "187 - Passion fruit" },
    { label: "188 - Mango fruit", value: "188 - Mango fruit" },
    { label: "189 - Kiwi fruit", value: "189 - Kiwi fruit" },
    { label: "194 - Avocado", value: "194 - Avocado" },
    { label: "118 - Hake", value: "118 - Hake" },
    { label: "119 - Crab", value: "119 - Crab" },
    { label: "120 -Shrimp", value: "120 -Shrimp" },
    { label: "131 - Oyster", value: "131 - Oyster" },
    { label: "135 - Spiny lobster", value: "135 - Spiny lobster" },
    { label: "138 - Whiting", value: "138 - Whiting" },
    { label: "139 - Mussel", value: "139 - Mussel" },
    { label: "162 - Sardine", value: "162 - Sardine" },
    { label: "166 - Tuna", value: "166 - Tuna" },
    { label: "193 - Cod", value: "193 - Cod" },
    { label: "125 -Fresh water fishing", value: "125 -Fresh water fishing" },
]

export const gccproduct = [
    {label: 'Staloral Animal Origin Initial', value:'Staloral Animal Origin Initial'},
    {label: 'Staloral Animal Origin Maintenance', value:'Staloral Animal Origin Maintenance'},
    {label: 'Staloral Mites Initial', value:'Staloral Mites Initial'},
    {label: 'Staloral Mites Maintenance', value:'Staloral Mites Maintenance'},
    {label: 'Staloral Moulds Maintenance', value:'Staloral Moulds Maintenance'},
    {label: 'Staloral Pollens initial', value:'Staloral Pollens initial'},
    {label: 'Staloral Pollens Maintenance', value:'Staloral Pollens Maintenance'},
]

export const chproduct = [
    {label: 'STALORAL 300, 3 Trees', value:'STALORAL 300, 3 Trees'},
    {label: 'STALORAL 300 Birch', value:'STALORAL 300 Birch'},
]

export const eunatproduct = [
    {label: 'STALORAL, aerosols lietošanai zem mēles, šķīdums', value: 'STALORAL, aerosols lietošanai zem mēles, šķīdums'},
    {label: 'STALORAL', value: 'STALORAL'},
    {label: 'STALORAL 300', value: 'STALORAL 300'},
    {label: 'Staloral Birke/Erle/Hasel', value: 'Staloral Birke/Erle/Hasel'},
    {label: 'STALORAL Birke', value: 'STALORAL Birke'},
    {label: 'STALORAL 5 Grasses', value: 'STALORAL 5 Grasses'},
    {label: 'STALORAL Alternaria', value: 'STALORAL Alternaria'},
    {label: 'STALORAL Birch', value: 'STALORAL Birch'},
    {label: 'STALORAL Cat', value: 'STALORAL Cat'},
    {label: 'STALORAL Cupressaceae', value: 'STALORAL Cupressaceae'},
    {label: 'STALORAL Dermatophagoides farinae', value: 'STALORAL Dermatophagoides farinae'},
    {label: 'STALORAL Dog', value: 'STALORAL Dog'},
    {label: 'STALORAL Dermatophagoides pteronyssinus', value: 'STALORAL Dermatophagoides pteronyssinus'},
    {label: 'STALORAL Erect Wall Pellitory', value: 'STALORAL Erect Wall Pellitory'},
    {label: 'STALORAL House Dust Mites', value: 'STALORAL House Dust Mites'},
    {label: 'STALORAL Mugwort', value: 'STALORAL Mugwort'},
    {label: 'STALORAL Olive', value: 'STALORAL Olive'},
    {label: 'STALORAL Ragweed', value: 'STALORAL Ragweed'},
]

export const eunatcountry = [
    {label: 'Austria', value: 'Austria'},
    {label: 'Bulgaria', value: 'Bulgaria'},
    {label: 'Czech republic', value: 'Czech republic'},
    {label: 'Hungary', value: 'Hungary'},
    {label: 'Latvia', value: 'Latvia'},
    {label: 'Lithuania', value: 'Lithuania'},
    {label: 'Luxembourg', value: 'Luxembourg'},
    {label: 'Poland', value: 'Poland'},
    {label: 'Romania', value: 'Romania'},
    {label: 'Slovak Rep', value: 'Slovak Rep'},
    {label: 'Slovenia', value: 'Slovenia'},
    {label: 'Germany', value: 'Germany'},
    {label: 'Italy', value: 'Italy'},
]

export const gcccountry = [
    {label: 'Bahrain', value: 'Bahrain'},
    {label: 'KSA', value: 'KSA'},
    {label: 'Kuwait', value: 'Kuwait'},
    {label: 'Qatar', value: 'Qatar'},
    {label: 'Sultanate of Oman', value: 'Sultanate of Oman'},
    {label: 'United Arab Emirates', value: 'United Arab Emirates'},
]

export const formattingRegion = [
    { label: 'EU', value: 'EU' },
    { label: 'GCC', value: 'GCC' },
    { label: 'CH', value: 'CH' },
    { label: 'Asia', value: 'Asia' },
    { label: 'US', value: 'US' },
    { label: 'Africa', value: 'Africa' },
]

export const publishingRegion = [
    { label: 'EU', value: 'EU' },
    { label: 'GCC', value: 'GCC' },
    { label: 'CH', value: 'CH' },
]